services:
  backend:
    image: templates-backend
    build:
      context: ..
      dockerfile: docker/DockerfileBackend

    container_name: templates-backend
    restart: always
    ports:
      - "19998:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest

    container_name: templates-backend-db
    restart: always

    environment:
      POSTGRES_DB: templates
      POSTGRES_USER: templates
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../../templates_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U templates" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ..
      dockerfile: docker/DockerfileFrontend
    ulimits:
      nofile: 5000
    image: templates-frontend

    container_name: templates-frontend
    restart: always

    ports:
      - "19997:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - backend
