version: '3'
services:
  db:
    image: postgres:latest
    container_name: templates-backend-dev-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: templates
      POSTGRES_USER: templates
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../../templates_postgres_data:/var/lib/postgresql/data
